baseurl: https://example.com
disablePathToLower: false
languageCode: hu
title: Dunai szemle
theme: Hugo-Octopress
paginate: 6
permalinks:
  post: /blog/:year-:month-:day-:title/
params:
  author: Dunai Szemle szerkesztők
  favicon: "duna.png"
  bitbucket: https://bitbucket.org/parsiya/
  continueReadingText: Tovább &rarr;
  description: ''
  customCSS:
    - css/custom.css
  disableGoogleFonts: true
  disableReadingTime: false
  generateTaxonomyList: true
  github: https://github.com/parsiya/Hugo-Octopress
  navigationNewWindow: true
  notFoundHeader: Itt nem található semmi
  notFoundText: 'Please either go back or use the navigation/sidebar menus.\r\n  '
  rss: true
  searchEngineURL: https://www.google.com/search
  sidebarHeader: Újdonságok
  sidebarMenuEnabled: true
  sidebarMenuHeader: Linkek
  sidebarRecentLimit: 5
  sidebarText: 'Független magyar közéleti, kulturális és regionális szemle
  a Duna mellől.'
  subtitle: Áttekintés Európa közepéről
  textrss: false
  truncate: true
  twitter: https://twitter.com/cryptogangsta/
menu:
  main:
    - name: "'26"
    - Name: Gazdaság
      URL: /categories/kl%C3%ADmav%C3%A1ltoz%C3%A1s/
    - Name: Társadalom
      URL: /categories/kl%C3%ADmav%C3%A1ltoz%C3%A1s/
    - Name: Kult
      URL: /categories/kl%C3%ADmav%C3%A1ltoz%C3%A1s/
    - Name: "Tech"
      URL: /categories/kl%C3%ADmav%C3%A1ltoz%C3%A1s/
    - Name: Duna
      URL: /categories/kl%C3%ADmav%C3%A1ltoz%C3%A1s/
    - Name: Európa
      URL: /categories/kl%C3%ADmav%C3%A1ltoz%C3%A1s/
    - Name: Klíma
      URL: /categories/kl%C3%ADmav%C3%A1ltoz%C3%A1s/
    - Name: Substack
      URL: https://www.example.net/
      weight: -5
  sidebar:
    - Name: example.net
      URL: https://www.example.net
      weight: 0
    - Name: This theme on Github
      URL: https://www.github.com/parsiya/hugo-octopress
      weight: 1
    - Name: Rólunk
      URL: /rolunk/
      weight: 2
markup:
  highlight:
    style: solarized-dark
  tableOfContents:
    endLevel: 8
    startLevel: 1
