baseurl: https://example.com
disablePathToLower: false
languageCode: en-us
title: Site title
theme: Hugo-Octopress
paginate: 6
permalinks:
  post: /blog/:year-:month-:day-:title/
params:
  author: Author
  bitbucket: https://bitbucket.org/parsiya/
  continueReadingText: Would you like to know more? &rarr;
  description: ''
  disableGoogleFonts: true
  disableReadingTime: false
  generateTaxonomyList: true
  github: https://github.com/parsiya/Hugo-Octopress
  navigationNewWindow: true
  notFoundHeader: There's nothing here
  notFoundText: 'Please either go back or use the navigation/sidebar menus.\r\n  '
  rss: true
  searchEngineURL: https://www.google.com/search
  sidebarHeader: Sidebar Header
  sidebarMenuEnabled: true
  sidebarMenuHeader: Sidebar Links
  sidebarRecentLimit: 5
  sidebarText: 'Here''s a [link to example.net](https://www.example.net)\r\n\r\n  New
    paragraph\r\n\r\n  Another paragraph which has two spaces in the end to create
    a new line using markdown  \r\n  New line but not a new paragraph\r\n  '
  subtitle: Subtitle appears under the website title
  textrss: false
  truncate: true
  twitter: https://twitter.com/cryptogangsta/
menu:
  main:
    - Name: example.net
      URL: https://www.example.net/
      weight: -5
    - Name: This theme on Github
      URL: https://www.github.com/parsiya/hugo-octopress
  sidebar:
    - Name: example.net
      URL: https://www.example.net
      weight: 0
    - Name: This theme on Github
      URL: https://www.github.com/parsiya/hugo-octopress
      weight: 1
markup:
  highlight:
    style: solarized-dark
  tableOfContents:
    endLevel: 8
    startLevel: 1
